ALTER TABLE tb_detail_po
  ADD COLUMN IF NOT EXISTS is_bonus TINYINT(1) NOT NULL DEFAULT 0 AFTER hrg_total_diskon,
  ADD COLUMN IF NOT EXISTS keterangan_bonus VARCHAR(255) NOT NULL DEFAULT '' AFTER is_bonus;

ALTER TABLE tb_po
  MODIFY hrg_pajak DOUBLE NOT NULL DEFAULT 0,
  MODIFY acc_with VARCHAR(25) NOT NULL DEFAULT '',
  MODIFY kd_printout_note VARCHAR(25) NOT NULL DEFAULT '';

ALTER TABLE tb_note_direktur
  MODIFY create_at TEXT NOT NULL DEFAULT '';

ALTER TABLE tb_note_barang
  MODIFY color_box TEXT NOT NULL DEFAULT '';

ALTER TABLE tb_tmp_item
  MODIFY kd_user VARCHAR(25) NOT NULL DEFAULT '',
  MODIFY is_bonus VARCHAR(50) NOT NULL DEFAULT '0',
  MODIFY keterangan_bonus VARCHAR(255) NOT NULL DEFAULT '';
