<?php
$h = static function ($value) { return htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8'); };
$money = static function ($value) { return 'Rp ' . number_format((float) $value, 0, ',', '.'); };
$vendorName = $request->nama_vendor ?: $request->vendor_usulan;
?>
<div class="content-wrapper">
  <div class="content-header"><div class="container-fluid"><div class="row mb-2"><div class="col-sm-7"><h1 class="m-0">Detail Workflow PO Jasa</h1><span class="text-muted"><?= $h($request->kd_po_jasa) ?></span> <span id="workflowDetailStatus" class="badge badge-info"><?= $h($request->status) ?></span></div><div class="col-sm-5 text-right"><a href="<?= base_url('pojasa/workflow') ?>" class="btn btn-default"><i class="fas fa-arrow-left mr-1"></i> Daftar kerja</a><?php if (in_array($workflow_role, array('ADMIN', 'PURCHASING', 'DIREKTUR'), true)) : ?><a href="<?= base_url('pojasa/purchasing/detail/' . rawurlencode($request->kd_po_jasa)) ?>" class="btn btn-warning"><i class="fas fa-shopping-cart mr-1"></i> Purchasing</a><?php endif; ?><?php if (!empty($request->no_spk)) : ?><a href="<?= base_url('pojasa/spk/' . rawurlencode($request->kd_po_jasa)) ?>" class="btn btn-info"><i class="fas fa-file-contract mr-1"></i> SPK</a><?php endif; ?><button type="button" id="workflowDetailProcess" class="btn btn-success btn-workflow-process <?= $allowed_actions ? '' : 'd-none' ?>" data-code="<?= $h($request->kd_po_jasa) ?>"><i class="fas fa-clipboard-check mr-1"></i> Proses</button></div></div></div></div>
  <section class="content"><div class="container-fluid">
    <div class="row"><div class="col-lg-8"><div class="card card-outline card-primary"><div class="card-header"><h3 class="card-title">Informasi Request</h3></div><div class="card-body">
      <div class="row"><div class="col-md-6"><dl class="row mb-0"><dt class="col-5">PIC</dt><dd class="col-7"><?= $h($request->nm_user) ?></dd><dt class="col-5">Departemen</dt><dd class="col-7"><?= $h($request->departemen) ?></dd><dt class="col-5">Tanggal</dt><dd class="col-7"><?= $h($request->tgl_request) ?></dd></dl></div><div class="col-md-6"><dl class="row mb-0"><dt class="col-5">Vendor</dt><dd class="col-7" id="workflowDetailVendor"><?= $h($vendorName ?: '-') ?></dd><dt class="col-5">Jadwal</dt><dd class="col-7"><?= $h(($request->tgl_mulai_pekerjaan ?: '-') . ' s/d ' . ($request->tgl_selesai_pekerjaan ?: '-')) ?></dd><dt class="col-5">Revisi</dt><dd class="col-7" id="workflowDetailRevision"><?= (int) $request->revision_no ?></dd></dl></div></div><hr><strong>Tujuan pekerjaan</strong><p style="white-space:pre-wrap" class="mb-2"><?= $h($request->tujuan_pekerjaan) ?></p><strong>Lokasi</strong><p class="mb-0"><?= $h($request->lokasi_pekerjaan ?: '-') ?></p>
    </div></div></div><div class="col-lg-4"><div class="small-box bg-info"><div class="inner"><h3 id="workflowDetailGrandTotal"><?= $money($request->estimasi_total) ?></h3><p>Total estimasi</p></div><div class="icon"><i class="fas fa-calculator"></i></div></div><div class="card"><div class="card-body p-2"><div class="d-flex justify-content-between"><span>Jasa</span><strong id="workflowDetailScopeTotal"><?= $money($request->estimasi_total_jasa) ?></strong></div><div class="d-flex justify-content-between"><span>Material</span><strong id="workflowDetailMaterialTotal"><?= $money($request->estimasi_total_bahan) ?></strong></div></div></div></div></div>

    <?php if ($can_edit_purchasing) : ?>
    <div class="card card-outline card-warning" id="purchasingReviewCard"><div class="card-header"><h3 class="card-title"><i class="fas fa-edit mr-1"></i> Review / Perbaikan Purchasing</h3></div><div class="card-body">
      <input type="hidden" id="workflowDetailCode" value="<?= $h($request->kd_po_jasa) ?>"><input type="hidden" id="workflowDetailVersion" value="<?= (int) $request->status_version ?>"><input type="hidden" id="workflowDetailExpectedStatus" value="<?= $h($request->status) ?>">
      <div class="row"><div class="col-md-4"><div class="form-group"><label>Vendor terpilih</label><select id="workflowPurchasingVendor" class="form-control"><option value="">-- Belum dipilih --</option><?php foreach ($vendors as $vendor) : ?><option value="<?= $h($vendor['kd_vendor_jasa']) ?>" <?= $request->kd_vendor_jasa === $vendor['kd_vendor_jasa'] ? 'selected' : '' ?>><?= $h($vendor['nama_vendor']) ?></option><?php endforeach; ?></select></div></div><div class="col-md-2"><div class="form-group"><label>Mulai</label><input id="workflowStartDate" type="date" class="form-control" value="<?= $h($request->tgl_mulai_pekerjaan) ?>"></div></div><div class="col-md-2"><div class="form-group"><label>Selesai</label><input id="workflowEndDate" type="date" class="form-control" value="<?= $h($request->tgl_selesai_pekerjaan) ?>"></div></div><div class="col-md-4"><div class="form-group"><label>Catatan Purchasing <?= strpos($request->status, 'REVISI_PURCHASING_') === 0 ? '<span class="text-danger">*</span>' : '' ?></label><textarea id="workflowPurchasingNote" rows="2" maxlength="5000" class="form-control"><?= $h($request->purchasing_note) ?></textarea></div></div></div>
      <div class="alert alert-light border">Perbarui estimasi yang diminta approver, simpan review, kemudian gunakan tombol Proses untuk mengajukan ke approver berikutnya.</div>
      <button type="button" id="workflowSavePurchasing" class="btn btn-warning"><i class="fas fa-save mr-1"></i> Simpan Review/Perbaikan</button>
    </div></div>
    <?php else : ?><input type="hidden" id="workflowDetailCode" value="<?= $h($request->kd_po_jasa) ?>"><input type="hidden" id="workflowDetailVersion" value="<?= (int) $request->status_version ?>"><input type="hidden" id="workflowDetailExpectedStatus" value="<?= $h($request->status) ?>"><?php endif; ?>

    <div class="card"><div class="card-header p-2"><ul class="nav nav-pills"><li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#workflowScopeTab">Scope & Material</a></li><li class="nav-item"><a class="nav-link" data-toggle="tab" href="#workflowDocumentTab">Dokumen</a></li><li class="nav-item"><a class="nav-link" data-toggle="tab" href="#workflowHistoryTab">Timeline Approval</a></li><li class="nav-item"><a class="nav-link" data-toggle="tab" href="#workflowRevisionTab">Revisi</a></li></ul></div><div class="card-body"><div class="tab-content">
      <div class="tab-pane active" id="workflowScopeTab"><h5>Scope pekerjaan</h5><div class="table-responsive mb-4"><table id="workflowScopeTable" class="table table-sm table-bordered"><thead><tr><th>#</th><th>Scope / Deskripsi</th><th>Qty</th><th>Satuan</th><th>Estimasi</th><th>Keterangan Purchasing</th></tr></thead><tbody><?php if (!$scopes) : ?><tr><td colspan="6" class="text-center text-muted">Belum ada scope.</td></tr><?php endif; ?><?php foreach ($scopes as $row) : ?><tr data-line="<?= (int) $row['line_no'] ?>"><td><?= (int) $row['line_no'] ?></td><td><?php if ($can_edit_purchasing) : ?><input class="form-control form-control-sm workflow-name mb-1" maxlength="255" placeholder="Nama scope pekerjaan" value="<?= $h($row['nama_scope']) ?>"><textarea class="form-control form-control-sm workflow-description" maxlength="5000" placeholder="Deskripsi scope pekerjaan"><?= $h($row['deskripsi']) ?></textarea><?php else : ?><?= $h($row['nama_scope']) ?><br><small><?= $h($row['deskripsi']) ?></small><?php endif; ?></td><td><?php if ($can_edit_purchasing) : ?><input type="number" min="0.01" step="0.01" class="form-control form-control-sm workflow-qty" placeholder="Qty" value="<?= $h($row['qty']) ?>"><?php else : ?><?= $h($row['qty']) ?><?php endif; ?></td><td><?php if ($can_edit_purchasing) : ?><input class="form-control form-control-sm workflow-unit" maxlength="50" placeholder="Satuan" value="<?= $h($row['satuan']) ?>"><?php else : ?><?= $h($row['satuan']) ?><?php endif; ?></td><td><?php if ($can_edit_purchasing) : ?><input type="number" min="0" step="0.01" class="form-control form-control-sm workflow-price" placeholder="Harga estimasi" value="<?= $h($row['harga_estimasi']) ?>"><?php else : ?><?= $money($row['harga_estimasi']) ?><?php endif; ?></td><td><?php if ($can_edit_purchasing) : ?><textarea class="form-control form-control-sm workflow-scope-note" rows="2" maxlength="5000" placeholder="Catatan Purchasing untuk scope"><?= $h($row['keterangan_purchasing']) ?></textarea><?php else : ?><?= $h($row['keterangan_purchasing'] ?: '-') ?><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div>
      <h5>Material / alat dan bahan</h5><div class="table-responsive"><table id="workflowMaterialTable" class="table table-sm table-bordered"><thead><tr><th>#</th><th>Material / Deskripsi</th><th>Kebutuhan</th><th>Reservasi</th><th>Draft aktif</th><th>Sisa</th><th>Sumber / Status</th><th>Estimasi</th><th>Aksi</th></tr></thead><tbody><?php if (!$materials) : ?><tr><td colspan="9" class="text-center text-muted">Belum ada material.</td></tr><?php endif; ?><?php foreach ($materials as $row) : ?><tr data-line="<?= (int) $row['line_no'] ?>" data-material="<?= (int) $row['id_material'] ?>"><td><?= (int) $row['line_no'] ?></td><td><?php if ($can_edit_purchasing) : ?><input class="form-control form-control-sm workflow-name mb-1" maxlength="255" placeholder="Nama material" value="<?= $h($row['nama_material']) ?>" <?= $row['planning_locked'] ? 'readonly' : '' ?>><textarea class="form-control form-control-sm workflow-description" maxlength="5000" placeholder="Deskripsi material" <?= $row['planning_locked'] ? 'readonly' : '' ?>><?= $h($row['deskripsi']) ?></textarea><?php else : ?><?= $h($row['nama_material']) ?><br><small><?= $h($row['deskripsi']) ?></small><?php endif; ?></td><td><?php if ($can_edit_purchasing) : ?><input type="number" min="0.01" step="0.01" class="form-control form-control-sm workflow-qty" placeholder="Qty kebutuhan" value="<?= $h($row['qty_kebutuhan']) ?>" <?= $row['planning_locked'] ? 'readonly' : '' ?>><input class="form-control form-control-sm workflow-unit mt-1" maxlength="50" placeholder="Satuan" value="<?= $h($row['satuan']) ?>" <?= $row['planning_locked'] ? 'readonly' : '' ?>><?php else : ?><?= $h($row['qty_kebutuhan'] . ' ' . $row['satuan']) ?><?php endif; ?></td><td class="js-reserved"><?= $h($row['reserved_qty']) ?></td><td class="js-draft"><?= $h($row['active_draft_qty']) ?></td><td class="js-remaining font-weight-bold"><?= $h($row['remaining_need']) ?></td><td><span class="badge badge-secondary js-source"><?= $h($row['computed_source']) ?></span><br><small class="js-fulfillment"><?= $h($row['fulfillment_status']) ?></small></td><td><?php if ($can_edit_purchasing) : ?><input type="number" min="0" step="0.01" class="form-control form-control-sm workflow-price" placeholder="Harga estimasi" value="<?= $h($row['harga_estimasi']) ?>"><?php else : ?><?= $money($row['harga_estimasi']) ?><?php endif; ?></td><td><button type="button" class="btn btn-xs btn-outline-info workflow-planning-detail" data-type="allocation" title="Detail reservasi"><i class="fas fa-boxes"></i></button> <button type="button" class="btn btn-xs btn-outline-warning workflow-planning-detail" data-type="draft" title="Detail draft"><i class="fas fa-shopping-cart"></i></button></td></tr><?php endforeach; ?></tbody></table></div></div>
      <div class="tab-pane" id="workflowDocumentTab"><div class="row">
        <?php if (!$documents) : ?><div class="col-12 text-muted text-center">Belum ada dokumen.</div><?php endif; ?>
        <?php foreach ($documents as $document) : ?>
          <?php $ext = strtolower(pathinfo($document['file_original'], PATHINFO_EXTENSION)); $isImage = in_array($ext, array('jpg','jpeg','png'), true); $isPdf = $ext === 'pdf'; ?>
          <div class="col-md-4 mb-3"><div class="border rounded p-2 h-100">
            <?php if ($isImage) : ?><button type="button" class="btn btn-link p-0 w-100 workflow-document-preview" data-type="image" data-url="<?= base_url('pojasa/workflow/document/' . (int) $document['id_dokumen'] . '/preview') ?>" data-title="<?= $h($document['file_original']) ?>"><img src="<?= base_url('pojasa/workflow/document/' . (int) $document['id_dokumen'] . '/preview') ?>" alt="Thumbnail dokumen" class="img-fluid rounded" style="height:150px;width:100%;object-fit:cover"></button><?php else : ?><div class="text-center text-secondary py-3"><i class="fas <?= $isPdf ? 'fa-file-pdf text-danger' : 'fa-file-alt' ?> fa-3x"></i></div><?php endif; ?>
            <strong class="d-block text-truncate"><?= $h($document['file_original']) ?></strong>
            <small class="text-muted d-block"><?= $h(strtoupper($ext)) ?> · <?= $h($document['jenis_dokumen']) ?> · Revisi <?= (int) $document['revision_no'] ?></small>
            <small class="text-muted d-block">Uploader: <?= $h($document['uploader_name'] ?: '-') ?> · <?= $h($document['created_at']) ?> · <?= number_format((int) $document['file_size_bytes'] / 1024, 1, ',', '.') ?> KB</small>
            <?php if ($isImage || $isPdf) : ?><button type="button" class="btn btn-xs btn-info mt-2 workflow-document-preview" data-type="<?= $isPdf ? 'pdf' : 'image' ?>" data-url="<?= base_url('pojasa/workflow/document/' . (int) $document['id_dokumen'] . '/preview') ?>" data-title="<?= $h($document['file_original']) ?>">Preview</button><?php endif; ?>
            <a class="btn btn-xs btn-secondary mt-2" href="<?= base_url('pojasa/workflow/document/' . (int) $document['id_dokumen'] . '/download') ?>">Download</a>
          </div></div>
        <?php endforeach; ?>
      </div></div>
      <div class="tab-pane" id="workflowHistoryTab"><div class="table-responsive"><table class="table table-sm table-bordered"><thead><tr><th>Waktu</th><th>Tahap</th><th>Aksi</th><th>Status</th><th>Aktor</th><th>Catatan</th></tr></thead><tbody id="workflowDetailApprovals"><?php if (!$history['approvals']) : ?><tr><td colspan="6" class="text-center text-muted">Belum ada approval.</td></tr><?php endif; ?><?php foreach ($history['approvals'] as $row) : ?><tr><td><?= $h($row['created_at']) ?></td><td><?= $h($row['approval_stage']) ?></td><td><?= $h($row['action']) ?></td><td><?= $h($row['from_status']) ?> → <?= $h($row['to_status']) ?></td><td><?= $h($row['actor_code']) ?> (<?= $h($row['actor_role']) ?>)</td><td><?= $h($row['catatan']) ?></td></tr><?php endforeach; ?></tbody></table></div></div>
      <div class="tab-pane" id="workflowRevisionTab"><div class="table-responsive"><table class="table table-sm table-bordered"><thead><tr><th>Revisi</th><th>Sumber</th><th>Diminta</th><th>Alasan</th><th>Diajukan ulang</th></tr></thead><tbody id="workflowDetailRevisions"><?php if (!$history['revisions']) : ?><tr><td colspan="5" class="text-center text-muted">Belum ada revisi.</td></tr><?php endif; ?><?php foreach ($history['revisions'] as $row) : ?><tr><td><?= (int) $row['revision_no'] ?></td><td><?= $h($row['revision_source']) ?></td><td><?= $h($row['requested_at']) ?></td><td><?= $h($row['alasan_revisi']) ?></td><td><?= $h($row['submitted_at'] ?: '-') ?></td></tr><?php endforeach; ?></tbody></table></div></div>
    </div></div></div>
  </div></section>
</div>
<?php $this->load->view('content/po/jasa/workflow/modal'); ?>
<div class="modal fade" id="workflowDocumentModal" tabindex="-1" role="dialog" aria-hidden="true"><div class="modal-dialog modal-xl" role="document"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="workflowDocumentTitle">Preview dokumen</h5><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div><div class="modal-body text-center" id="workflowDocumentBody"></div></div></div></div>
<div class="modal fade" id="workflowPlanningModal" tabindex="-1" role="dialog" aria-hidden="true"><div class="modal-dialog modal-lg" role="document"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Detail pemenuhan material</h5><button type="button" class="close" data-dismiss="modal"><span>&times;</span></button></div><div class="modal-body"><div class="table-responsive"><table class="table table-sm table-bordered"><thead id="workflowPlanningHead"></thead><tbody id="workflowPlanningBody"></tbody></table></div></div></div></div></div>
